# Generated by Django 5.0.2 on 2024-02-14 19:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Berry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='название')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость')),
            ],
            options={
                'verbose_name': 'ягода',
                'verbose_name_plural': 'ягоды',
            },
        ),
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='название')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость')),
            ],
            options={
                'verbose_name': 'украшение',
                'verbose_name_plural': 'украшения',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='количество уровней')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость')),
            ],
            options={
                'verbose_name': 'уровень',
                'verbose_name_plural': 'уровни',
            },
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='название')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость')),
            ],
            options={
                'verbose_name': 'форма',
                'verbose_name_plural': 'формы',
            },
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='название')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость')),
            ],
            options={
                'verbose_name': 'топпинг',
                'verbose_name_plural': 'топпинги',
            },
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=75, verbose_name='надпись')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость')),
                ('berries', models.ManyToManyField(related_name='cakes', to='cakes.berry', verbose_name='ягоды')),
                ('decorations', models.ManyToManyField(related_name='cakes', to='cakes.decoration', verbose_name='украшения')),
                ('levels', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cakes', to='cakes.level', verbose_name='количество уровней')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cakes', to='cakes.shape', verbose_name='форма торта')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cakes', to='cakes.topping', verbose_name='топпинг')),
            ],
            options={
                'verbose_name': 'торт',
                'verbose_name_plural': 'торты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='адрес')),
                ('notes', models.TextField(blank=True, verbose_name='примечание')),
                ('delivery_date', models.DateField(verbose_name='дата доставки')),
                ('delivery_time', models.TimeField(verbose_name='время доставки')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость заказа')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cakes.cake', verbose_name='торт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
    ]
