# Generated by Django 5.0.2 on 2024-02-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shape',
            new_name='Form',
        ),
        migrations.RenameField(
            model_name='cake',
            old_name='shape',
            new_name='form',
        ),
    ]
