# Generated by Django 5.0.2 on 2024-02-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0004_remove_cake_berries_remove_cake_decorations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='notes',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_notes',
            field=models.TextField(blank=True, verbose_name='примечание для курьера'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_notes',
            field=models.TextField(blank=True, verbose_name='примечание к заказу'),
        ),
    ]
