# Generated by Django 5.0.2 on 2024-02-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0005_remove_order_notes_order_delivery_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='заказ завершён'),
        ),
    ]
